### ISSUE TITLE
fftw3.h is missing

### ISSUE THREAD

**Issue by jazzman31** [OlliV/DiaPro#14]
Hi Olliv,
I just tried to compile your project but whatever I've tried so I couldn't get it work :) 
-  I'm on Mac book pro which has MacOs Big Sur(Intel)
-  I've added FFT lib.a on the project
-  I guess ASPIK needs the FFTW folder with x64 sub folder but I'm not sure how did you add this fftw3.h on your project...

As I said I've tried everything but even VST SDK 3.7.3 but sadly I couldn't debug anytime :)

Cheers,
Jan

**Comment by OlliV** [comment]
Hi,

Sorry I didn't see the notification until now.

That's strange. I'm running on Intel too.

So, I recently changed the build to make it universal (Intel & M1).
I changed the way `fft` is installed because `brew` doesn't support universal stuff.

What you should do before running the build is:

```
cd fftw
./runme.sh
```

This will download the correct library versions from GitHub using Brew's repos.

Just a heads up, I'm working on releasing a signed binary package of the VST. I got enrolled into the Apple Developer Program a few weeks ago but didn't have time to figure out how to do everything.

**Comment by OlliV** [comment]
I have made a signed and stapled release here https://github.com/OlliV/DiaPro/releases/tag/v2.0.0.2

To my understanding this binary should be accepted by any recent macOS version without touching any security settings.
You just need to extract the zip and move the VST3 plugin to `~/Library/Audio/Plug-Ins/VST3/`.
